version: '3'

services:
  server:
    build: '.'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    links:
      - db
    ports:
      - '3000:3000'

  db:
    image: 'mongo:4.4.6'
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/usr/local/var/mongodb
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'